---
title: "10-Fold fSIR"
output:
  html_document:
    df_print: paged
---

```{r import}
devtools:: install_github("elianachristou/fquantdr")
library(dplyr)
library(tidyverse)
library(ggplot2)
library(fquantdr)
library(caret)
library(fda)
library(vip)

NHANES <- readRDS('/Users/darrensummerlee/Library/CloudStorage/Dropbox/NHANES paper/data set/BP_stats_no_enhance.rds')
```

```{r data adjustment}
model_data <- data.frame(
  bpS = NHANES$BPS_avg,
  Gender = as.factor(NHANES$gender),
  BMI = NHANES$BMI,
  CHD = as.factor(NHANES$CHD),
  Age = NHANES$age
)

MIMS_array <- array(NHANES$MIMS, dim = c(nrow(NHANES$MIMS), ncol(NHANES$MIMS),1))
```

```{r 10-fold cross validation}
rmse_metric <- function(truth, estimate) {
  sqrt(mean((truth - estimate)^2))
}

set.seed(1)
folds <- createFolds(model_data$bpS, k = 10, list = TRUE)
cv_results <- data.frame(
  Fold = 1:10, RMSE = numeric(10), R_squared = numeric(10), Coverage = numeric(10)
)
importance_list <- list()

custom_predict <- function(object, newdata) { predict(object, newdata) }

for (i in 1:10) {
  cat("Processing Fold:", i, "\n")
  
  #train/test split
  test_idx <- folds[[i]]
  train_idx <- setdiff(1:nrow(model_data), test_idx)

  # Training data for FSIR
  MIMS_train <- MIMS_array[train_idx, , , drop = FALSE]
  Y_train <- model_data$bpS[train_idx]

  # Test data fo bpS and MIMS
  MIMS_test <- MIMS_array[test_idx, , , drop = FALSE]
  Y_test <- model_data$bpS[test_idx]

  # Fit FSIR, extract sufpreds
  nt <- dim(MIMS_array)[2]
  model_fsir <- mfsir(MIMS_train, Y_train, H = 5, nbasis = 20)
  FSIR1_train <- model_fsir$sufpred[, 1]
  FSIR2_train <- model_fsir$sufpred[, 2]

  # Functional representation of test data
  nt <- dim(MIMS_test)[2]
  MIMS_test_mat <- t(MIMS_test[, , 1]) 
  basis_obj <- create.bspline.basis(rangeval = c(1, nt), nbasis = 20)
  MIMS_test_fd <- Data2fd(argvals = 1:nt, y = MIMS_test_mat, basisobj = basis_obj)

  test_coef <- as.matrix(t(MIMS_test_fd$coefs)) 
  sufpred_test <- test_coef %*% model_fsir$phi
  FSIR1_test <- sufpred_test[, 1]
  FSIR2_test <- sufpred_test[, 2]
  
  #combine train/test data for lm
  fold_train_data <- data.frame(model_data[train_idx, ], FSIR1 = FSIR1_train, FSIR2 = FSIR2_train)
  fold_test_data <- data.frame(model_data[test_idx, ], FSIR1 = FSIR1_test, FSIR2 = FSIR2_test)

  # Linear model on training set
  model_lm <- lm(bpS ~ FSIR1 + FSIR2 + Gender + BMI + CHD + Age,
                 data = data.frame(model_data[train_idx, ],
                              FSIR1 = FSIR1_train, FSIR2 = FSIR2_train))

  # Predict lm on test set
  pred_obj <- predict(model_lm,
                    newdata = data.frame(model_data[test_idx, ], FSIR1 = FSIR1_test, FSIR2 = FSIR2_test),
                    interval = "prediction", level = 0.95)
  preds <- pred_obj[, "fit"]
  
  #RMSE
  residuals <- fold_test_data$bpS - preds
  cv_results$RMSE[i] <- sqrt(mean(residuals^2))
  #R^2
  cv_results$R_squared[i] <- summary(model_lm)$r.squared
  #Cov Rate
  within_interval <- Y_test >= pred_obj[, "lwr"] & Y_test <= pred_obj[, "upr"]
  cv_results$Coverage[i] <- mean(within_interval)
  
  #Variable Importance
  vi_fold <- vip(
    model_lm,
    method = "permute",
    train = fold_test_data,
    target = "bpS",
    metric = rmse_metric,
    pred_wrapper = custom_predict,
    nsim = 10,
    smaller_is_better = TRUE
  )
  
  vi_fold$data$Fold <- i
  importance_list[[i]] <- vi_fold$data
}
```

```{r metrics}
cat("10-fold FSIR Model:\n")
print(cv_results)
cat("RMSE:", round(mean(cv_results$RMSE), 2), "\n")
cat("R-squared:", round(mean(cv_results$R_squared), 3), "\n")
cat("95% Coverage Rate:", round(mean(cv_results$Coverage) * 100, 3), "%\n")
```

```{r variabel importance}
importance_df <- do.call(rbind, importance_list)

avg_importance <- importance_df %>%
  group_by(Variable) %>%
  summarise(
    Avg_Importance = mean(Importance),
    Std_Dev = sd(Importance)
  )

print(avg_importance)

ggplot(avg_importance, aes(x = reorder(Variable, Avg_Importance), y = Avg_Importance)) +
  geom_col(fill = "turquoise") +
  geom_errorbar(
    aes(ymin = Avg_Importance - Std_Dev, ymax = Avg_Importance + Std_Dev),
    width = 0.2
  ) +
  coord_flip() +
  labs(
    title = "Average Permutation Importance from 10-Fold CV",
    subtitle = "Error bars show standard deviation across folds",
    x = "Variable",
    y = "Average Increase in RMSE"
  ) +
  theme_minimal()
```

```{r heatmap}
results <- data.frame(actual = Y_test, predicted = as.vector(preds))

#2d color
zones <- data.frame(
  xmin = c(50, 100, 120, 130, 140),
  xmax = c(100, 120, 130, 140, Inf),
  fill = c("Low", "Normal", "Elevated", "ISH-S1", "S2"),
  color = c("lightblue", "green3", "yellow", "orange", "red")
)

zone_rects <- expand.grid(x = 1:nrow(zones), y = 1:nrow(zones))

max_risk_index <- pmax(zone_rects$x, zone_rects$y)
zone_rects <- cbind(
  zone_rects,
  xmin = zones$xmin[zone_rects$x],
  xmax = zones$xmax[zone_rects$x],
  ymin = zones$xmin[zone_rects$y],
  ymax = zones$xmax[zone_rects$y],
  fill = zones$color[max_risk_index]
)

ggplot() +
  geom_rect(data = zone_rects, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = fill), alpha = 0.4) +
  scale_fill_identity() +
  geom_point(data = results, aes(x = predicted, y = actual), color = "blue", size = 0.5) +
  geom_abline(intercept = -20, slope = 1, linetype = "dashed", color = "black", linewidth = 0.4) +
  geom_abline(intercept = 20, slope = 1, linetype = "dashed", color = "black", linewidth = 0.4) +
  xlim(50, 150) +
  ylim(50, 250) +
  coord_cartesian(xlim = c(50, 200), ylim = c(50, 200), expand = FALSE) +
  scale_x_continuous(breaks = c(50, 80, 100, 120, 140, 150)) +
  scale_y_continuous(breaks = c(50, 80, 100, 120, 140, 150)) +
  labs(x = "Predicted BP", y = "True BP") +
  coord_fixed() +
  theme_minimal()
```